# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17, 21]  # Current Java LTS & minimum supported by Minecraft, Current Java LTS
        # Run on both Linux and Windows
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Specify a stable version
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1  # Specify a stable version
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2  # Specify a stable version
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest Java on one OS
        uses: actions/upload-artifact@v2  # Specify a stable version
        with:
          name: Artifacts
          path: build/libs/
